#-------------------------------
# General Site Settings
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://www.prestonmalen.com" # The base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      disable: true
  math_engine_opts:
    preview: false

permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  style: compressed