#-------------------------------
# General Site Settings
title: "Preston Malen"
description: "Projects, Experience, and Everything in Between"
baseurl: ""                              # root site
url: "https://prestonmalen.com"       # or your custom domain

# Markdown + MathJax
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3
  math_engine: mathjax
  hard_wrap: false

# Permalinks (journal-style under /journal/)
permalink: /journal/:year/:month/:day/:title/

# Plugins (all allowed on GitHub Pages)
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 8
paginate_path: "/page/:num"

# Pages in /_pages get pretty permalinks
include:
  - _pages

defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

sass:
  style: compressed
