#-------------------------------
# Site Settings
title: Preston Malen
logo: # e.g. '/images/logo.png'
description:

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'Bio'
      url: '/bio/'
    - title: 'Journal'
      url: '/journal/'

#-------------------------------
# Author Settings
author:
  name: Preston Malen
  # avatar: '/images/15.jpg'   # set your own or remove

#-------------------------------
# Hero Settings
hero:
  title: Preston Malen
  description: Thoughts, notes, and projects.
  # image: '/images/01.jpg'    # set your own or remove

#-------------------------------
# Contact Settings
contact:
  email: your@email.com
  description: ""

#-------------------------------
# Footer section (trim to what you use)
social:
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com/pmalen327"}
