#-------------------------------
# Site Settings
title: Preston Malen
logo:
description:

#-------------------------------
# Navigation Settings
menu-settings:
  menu-items:
    - title: 'Home'
      url: '/'
    - title: 'Bio'
      url: '/bio/'
    - title: 'Journal'
      url: '/journal/'

#-------------------------------
# Author Settings
author:
  name: Preston Malen
  avatar:

#-------------------------------
# Hero Settings
hero:
  title: Preston Malen
  description: Thoughts, notes, and projects.
  image:

#-------------------------------
# Newsletter (disable)
mailchimp:
mailchimp-identifier:
mailchimp-button-text: